### ISSUE TITLE
Spelerslijst

### ISSUE THREAD

**Issue by Laoujin** [TTCErembodegem/TTC-React-Front#1]
* [x] exporteerbaar excel formaat voor VTTL/Sporta (Roep de oude TTC php api aan)
* [ ] twee views: tiles (Jorn) (met foto's) per team en een tabel (per team?)
* [x] de lijsten VTTL/Sporta met enkel die dingen die op verplaatsing moeten geweten zijn (ie de dingen die op het wedstrijdblad staan) moeten behouden blijven
* [x] text filter
* [x] iedereen kan zijn adres, telefoonnummer etc aanpassen --> bovenaan profile icon vanwaar dit allemaal kan gebeuren
* [x] iedereen kan beste slag van iedereen veranderen? (met history wie wat gedaan heeft:) --> lijkt me dan meer kans dat er iets met gebeurd
* [x] toon medespelers van de volgende match VTTL/Sporta bovenaan

**Comment by Laoujin** [comment]
ingelogd: 
- toon medespelers van de volgende match VTTL/Sporta bovenaan

**Comment by JornHeyvaert** [comment]
Waar kan ik dat php-script vinden voor de exporteerbare excel?

**Comment by Laoujin** [comment]
https://github.com/Laoujin/ttc/blob/master/admin/spelersexport.php
