### ISSUE TITLE
wedstrijdverslagen

### ISSUE THREAD

**Issue by Laoujin** [TTCErembodegem/TTC-React-Front#11]
* [x]  integreren van een discussie ding:  discours (!) of disqus - moet met emoticons, tekst opmaak, etc
discours etc is mss te veel voor nodig om op te zetten. ergens een HTML5 editor gebruiken?

* [x]  iedereen kan commentaar toevoegen aan een verslag: optie om publiek te maken
* [x]  profile: avatar speler plaatsen bij berichten
* [x]  foto's pagina van oude site gaat weg maar bij elk verslag kunnen foto's opgeladen worden...

match tile:
* [x]  Sporta A, Vttl D als eigen naam: Sporta D vs Nova A
* [x] datum beginnen en waar/wanneer afgesproken
* [x] wie speelt bij ons + details (gsm) + gaat rechtstreeks/aan de zaal/ophalen
* [x] ophalen welke tegenstanders er al gespeeld hebben bij de tegenstanders
* [x] +1 bij de scores kunnen emitten
* [x] real life comments/chat voor tijdens de matchen?
* [x]  google maps link naar locatie (foto's maken van locaties!?) + adres + douches
* [x] dingen die belangrijk zijn voor wedstrijdblad: wedstrijdnr, computer nr, klassement, waarde etc --> enkel op de dag zelf belangrijk
* [x] wedstrijdverslag 
* [x] terugronde: vorige uitslag en tegenstanders tonen

**Comment by Laoujin** [comment]
* [] Uitslagen sporta kunnen door gemaild worden
