### ISSUE TITLE
onboarding process

### ISSUE THREAD

**Issue by Laoujin** [TTCErembodegem/TTC-React-Front#16]
* [ ] FIRST login (with existing credentials)
* [ ] ask to verify adres, telephone, email, teams, ...
* [ ] upload new photo and/or thumbnail
