### ISSUE TITLE
profile

### ISSUE THREAD

**Issue by Laoujin** [TTCErembodegem/TTC-React-Front#2]
Als inloggen nog niet gedaan is, iets dummy dat return true doet? :)

* [x] eigen details kunnen wijzigen
* [x] eigen avatar / volledige foto opladen
* [x] notificatie wanneer iets toegevoegd aan comments waarop geabonneerd: matchen van jouw team, gestarde convos, convos waar je zelf iets bijgedragen hebt
* [x] wanneer je niet kan spelen: stel de speeldatums voor op een kalender? (mss beter gewoon een lijst)
* [x] zie de volledige kalender van je team: wie welke matchen speelt
