### ISSUE TITLE
Roadmap to v1

### ISSUE THREAD

**Issue by Laoujin** [TTCErembodegem/TTC-React-Front#24]
Voordat we live kunnen gaan:

* [x] Security: Inloggen & Cookie/JWT (of OAuth)
* [x] Afschermen ploegopstelling+speler contact details wanneer niet ingelogd
* [x] Speler.Toegang koppelen aan security.
* [x] Verslagen: Verslag door ploegspeler, commentaar door iedereen, optie om publiek te maken (security!)
* [x] Sockets om +1 bij thuis/bezoekers te doen
* [x] Startpagina met introductie + sponsers
* [x] Nieuw paswoord request (Jorn)

Optioneel: (anders v1.1)
* [x] Sponsers toevoegen aan links pagina (en ook 1 random sponser in de footer?)
* [x] Mobile: Match card tabs zijn niet goed, moet iets anders

For much win: (=officiële introductie in de club?)
* [x] Pagina met alle 4 de matchen open en projecteren op TV...
* [x] Hoe mobile gebruiken om internet te geven aan pc in clublokaal

Left over: 
* [x] DEV: Database seed om Sporta/Vttl & MatchPlayers op te vullen
* [x] **TtcAuthorizationFilterAttribute**: security for /signalR (send bearer with signalR how?)
* [x] Profiel: Spelers kunnen hun wachtwoord, contact informatie en foto aanpassen
* [x] deploy script

**Comment by JornHeyvaert** [comment]
In plaats van een random sponsor -> de hoofdsponsor 
of mss gewoon sponsors in links zonder ene in footer?
(waarschijnlijk ook te bespreken met Dirk fzo)

**Comment by Laoujin** [comment]
Het staat online:)
http://ttc-erembodegem.azurewebsites.net/

Nog wat extra dingen die nog moeten gebeuren: (wheeeee)
* [ ] Mobile: sponsors onder de title op kleine devices en sponsers ondereen ipv naasteen
* [ ] Mobile: spinning loader in het midden
* [ ] Performantie: Niet zo zot veel meer ophalen met de initialLoad, das daar nie al te rap precies :)
* [ ] Webpack: Release build. (tis nu 8MB, is da nie wa overdreven...)
* [ ] Verslag Editors: readonly prop
* [ ] MatchCardHeader tooltip (upgrade material-ui)?
* [ ] Match Card: Speler images op mobile (slechts 1 op mobile wss?)

**Comment by Laoujin** [comment]
Bug: MatchCardHeader tooltip is [Object object]
https://github.com/callemall/material-ui/issues/2218

Current v: v0.15.0-alpha.1

Releases:
https://github.com/callemall/material-ui/releases

... De volgende release upgraden en dat zou moeten gefixed zijn

**Comment by Laoujin** [comment]
Release build:
`npm run build release`
