### ISSUE TITLE
roadmap to v2

### ISSUE THREAD

**Issue by Laoujin** [TTCErembodegem/TTC-React-Front#62]
Hey Jorn,
Ik stop hier even mee (nog wat bugs opvolgen in productie maar voor de rest is dit denk ik een goeie eerste versie)

De roadmap voor v2:

In eerste instantie:
- [x] Ploegen: Dit zou mss de volgende meest interessante pagina kunnen zijn: De volledige kalender van elke ploeg - er was daar nu al vraag naar (Marc). De huidige ranking in de divisie kan daar ook komen.
  ---> Menu items: "Ploegkalender Vttl" en "Ploegkalender Sporta") --> lange text deftig op small device?
  ---> Tab per ploeg? (Component dat tabs toont en bij kleiner overgaat naar Accordeon)
- [x] De 2 problemen met te veel mysql calls oplossen
  --> Catch excpetion, en stuur naar frontend een "429 Too Many Requests"
  --> in frontend 3x dezelfde query opnieuw proberen
- [x] Na bovenstaande, de TEST erembodegem site opzetten
- [x] Op die TEST site checken waarom het niet werkt op Windows Phone
- [x] En daarna waarom het niet werkt op iPhone
- [x] Zet SYSTEM user pwd
- [x] Jorn FTP/mysql details mailen van TST en PRD; ook pwd van de SYSTEM user
- [x] Spelers: Excel export (Jelle gebruikte dit zelf op de oude site)
- [x] Admin: Spelers: Syncen met Frenoy (ie de nieuwe klassementen, ...); Nieuwe spelers; Spelers die niet meer ingeschreven zijn op speler.gestopt zetten.

In tweede instantie:
- [x] Profile: spelers kunnen hun eigen details wijzigen
- [ ] Match Card: Club informatie tab: Jan had allemaal up to date info (google maps, bestuur etc) van alle clubs (momenteel is dat maar een povere tab op de site) - die bij ons integreren zou fantastisch zijn :)
- [x] Admin pagina's: Aanpassen spelers (email, naam, lid, toegang, ...). Competitie stuff (klassementen, ...) moet niet door ons aangepast worden, dat kan allemaal via Frenoy. Nieuw lid kunnen toevoegen.
- [x] Admin pagina's: Aanpassen matchen: datum voor verleggen (wss enige dat niet 100% met Frenoy kan gesynced worden)
- [ ] Chat: Je kan nu zien wie aanlogt maar je kan hen niet bereiken... Chat is snel geïmplenteerd met SignalR :package: 

Voor de rest ga ik eens luisteren tijdens de volgende bestuursvergadering wat ze zouden willen...
Dirk DS sprak al over een pagina met de bestuursleden. Ik was aan het denken mss een pagina met een carousel met foto's van binnen/buiten de zaal en de bestuursleden daar ook bij zetten.

**Comment by Laoujin** [comment]
Als je wil kunnen we in een weekend nog eens afspreken. We zouden een feature samen kunnen ontwikkelen... Dan kan ik de manier van werken mss wat toelichten (Redux actions, reducers etc, de backend, enzo)

**Comment by Laoujin** [comment]
Ook todo:

* [ ] De 2 problemen met te veel mysql calls oplossen
* [ ] Na bovenstaande, de TEST erembodegem site opzetten
* [ ] Op die TEST site checken waarom het niet werkt op Windows Phone
* [ ] En daarna waarom het niet werkt op iPhone
* [ ] Zet SYSTEM user pwd
* [ ] Jorn FTP/mysql details mailen van TST en PRD; ook pwd van de SYSTEM user

**Comment by Laoujin** [comment]
Het eerste mysql probleem:
`mysql_max_connections`

Tweede:  
System.Data.Entity.Core.EntityException: The underlying provider failed on Open. ---> MySql.Data.MySqlClient.MySqlException: Unable to connect to any of the specified MySQL hosts.

**Comment by Laoujin** [comment]
Moet zeker nog gebeuren voor volgend seizoen:

* [ ] Spelers: Excel export (Jelle gebruikte dit zelf op de oude site)
* [ ] Admin: Spelers: Syncen met Frenoy (ie de nieuwe klassementen, ...); Nieuwe spelers; Spelers die niet meer ingeschreven zijn op speler.gestopt zetten.

**Comment by Laoujin** [comment]
bump

**Comment by Laoujin** [comment]
Test site beschikbaar op:
http://ttc-tst-webapp.azurewebsites.net/

Testen met iPhone zal voor morgen zijn mss :)
